<script>
export default {
  name: "ComponentName",
  components: {},
  filters: {},
  props: {},
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Tricorder CLI!",
    };
  },
  methods: {
    greeting() {
      alert(this.message);
    },
  },
  computed: {},
  watch: {},
  beforeMounted() {},
  mounted() {},
  beforeCreated() {},
  created() {},
  beforeUpdated() {},
  updated() {},
};
</script>

<template>
  <div class="page">
    <header class="header">
      <h2 class="title">ComponentName</h2>

      <button @click="greeting" class="action">Action</button>
    </header>

    <main class="content">
      <p>{{ message }}</p>
    </main>
  </div>
</template>

<style scoped>
.page {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  padding: 20px 40px;
}

.header {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  align-content: center;
}

.title {
  color: #333;
  font-size: x-large;
}

.content {
  display: flex;
  align-items: center;
  align-content: center;
  justify-content: center;
}
</style>
