<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'ResourceName',
  components: {},
  filters: {},
  props: {},
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Clingon CLI!"
    }
  },
  methods: {
    greeting() {
      alert(this.message)
    }
  },
  computed: {},
  watch: {},
  beforeMounted() {},
  mounted() {},
  beforeCreated() {},
  created() {},
  beforeUpdated() {},
  updated() {}
})
</script>

<template>
  <div :class="$style.page">
    <header :class="$style.header">
      <h2 :class="$style.title">ResourceName</h2>

      <button @click="greeting" :class="$style.action">Action</button>
    </header>

    <main :class="$style.content">
      <p>{{ message }}</p>
    </main>
  </div>
</template>

<style scoped module>
.page {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  padding: 20px 40px;
}

.header {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  align-content: center;
}

.title {
  color: #333;
  font-size: x-large;
}

.content {
  display: flex;
  align-items: center;
  align-content: center;
  justify-content: center;
}
</style>
