<template>
  <div class="page">
    <header class="header">
      <h2 class="title">ResourceName</h2>

      <button @click="greeting" class="action">Action</button>
    </header>

    <main class="content">
      <p>{{ message }}</p>
    </main>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'ResourceName',
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Clingon CLI!"
    }
  },
  methods: {
    greeting(): void {
      alert(this.message)
    }
  }
})
</script>

<style scoped>
.page,
.header,
.content {
  display: flex;
}

.header,
.content {
  align-items: center;
  align-content: center;
}

.page {
  flex-direction: column;
  justify-content: flex-start;
  padding: 20px 40px;
}

.header {
  flex-direction: row;
  justify-content: space-between;
}

.content {
  justify-content: center;
}

.title {
  color: #333;
  font-size: x-large;
}
</style>
