<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'ResourceName',
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Clingon CLI!"
    }
  },
  methods: {
    greeting(): void {
      alert(this.message)
    }
  }
})
</script>

<template>
  <div>
    <header>
      <h2>ResourceName</h2>

      <button @click="greeting">Action</button>
    </header>

    <main>
      <p>{{ message }}</p>
    </main>
  </div>
</template>
