<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "ResourceName",
  props: {},
  components: {},
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Tricorder CLI!",
    };
  },
  methods: {},
  computeds: {},
  watch: {},
  beforeMounted() {},
  mounted() {},
  beforeCreated() {},
  created() {},
  beforeUpdated() {},
  updated() {},
});
</script>

<template>
  <div class="flex justify-center items-center">
    <p class="text-slate-800">
      {{ message }}
    </p>
  </div>
</template>
