export type KebabCaseProps = {
  id: string
}

export function KebabCase({ id }: KebabCaseProps) {
  return (
    <div id={id}>
      <p>Hello, I'm a component, auto generated by Clingon CLI!</p>
    </div>
  )
}
