import { render, screen } from "@testing-library/react";

import ComponentName from "componentPath";

describe("ComponentName", () => {
  it("renders welcome message", () => {
    render(<ComponentName />);

    expect(
      screen.getByText(
        "Hello, I'm a component, auto generated by Tricorder CLI!"
      )
    ).toBeInTheDocument();
  });
});
