<template>
  <div class="component">
    <p class="paragraph">
      {{ message }}
    </p>
  </div>
</template>

<script>
export default {
  name: "ComponentName",
  components: {},
  filters: {},
  props: {},
  methods: {},
  computeds: {},
  watch: {},
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Tricorder CLI!",
    };
  },
  beforeMounted() {},
  mounted() {},
  beforeCreated() {},
  created() {},
  beforeUpdated() {},
  updated() {},
};
</script>

<style>
.component {
  display: flex;
  justify-content: center;
  align-items: center;
}

.paragraph {
  color: #333;
}
</style>
