<script setup lang="ts">
// * Data *

const message = "Hello, I'm a resource auto generated by Tricorder CLI!"
</script>

<template>
  <div :class="$style.component">
    <p :class="$style.message">
      {{ message }}
    </p>
  </div>
</template>

<style scoped module>
.component {
  display: flex;
  justify-content: center;
  align-items: center;
}

.message {
  color: #333;
}
</style>
