<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'ResourceName',
  components: {},
  filters: {},
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Clingon CLI!"
    }
  },
  props: {},
  methods: {},
  computed: {},
  watch: {},
  beforeMounted() {},
  mounted() {},
  beforeCreated() {},
  created() {},
  beforeUpdated() {},
  updated() {}
})
</script>

<template>
  <div class="component">
    <p class="message">
      {{ message }}
    </p>
  </div>
</template>

<style scoped>
.component {
  display: flex;
  justify-content: center;
  align-items: center;
}

.message {
  color: #333;
}
</style>
