<script>
export default {
  name: "ComponentName",
  props: {},
  components: {},
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Tricorder CLI!",
    };
  },
  methods: {},
  computeds: {},
  watch: {},
  beforeMounted() {},
  mounted() {},
  beforeCreated() {},
  created() {},
  beforeUpdated() {},
  updated() {},
};
</script>

<template>
  <div class="component">
    <p class="paragraph">
      {{ message }}
    </p>
  </div>
</template>

<style scoped>
.component {
  @apply flex justify-center items-center;
}

.paragraph {
  @apply text-slate-800;
}
</style>
