<script lang="ts">
const message = "Hello, I'm a resource auto generated by Tricorder CLI!";

function greeting() {
  alert(this.message);
}
</script>

<template>
  <div :class="$style.page">
    <header :class="$style.header">
      <h2 :class="$style.title">ComponentName</h2>

      <button @click="greeting" :class="$style.action">Action</button>
    </header>

    <main :class="$style.content">
      <p>{{ message }}</p>
    </main>
  </div>
</template>

<style scoped module>
.page {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  padding: 20px 40px;
}

.header {
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  align-content: center;
}

.title {
  color: #333;
  font-size: x-large;
}

.content {
  display: flex;
  align-items: center;
  align-content: center;
  justify-content: center;
}
</style>
