<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "ComponentName",
  components: {},
  filters: {},
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Tricorder CLI!",
    };
  },
  props: {},
  methods: {},
  computed: {},
  watch: {},
  beforeMounted() {},
  mounted() {},
  beforeCreated() {},
  created() {},
  beforeUpdated() {},
  updated() {},
});
</script>

<template>
  <div class="component">
    <p class="paragraph">
      {{ message }}
    </p>
  </div>
</template>

<style scoped>
.component {
  display: flex;
  justify-content: center;
  align-items: center;
}

.paragraph {
  color: #333;
}
</style>
