<script lang="ts">
const message = "Hello, I'm a resource auto generated by Tricorder CLI!";
</script>

<template>
  <div class="component">
    <p class="paragraph">
      {{ message }}
    </p>
  </div>
</template>

<style scoped>
.component {
  @apply flex justify-center items-center;
}

.paragraph {
  @apply text-slate-800;
}
</style>
