<script lang="ts">
const message = "Hello, I'm a resource auto generated by Tricorder CLI!";
</script>

<template>
  <div class="flex justify-center items-center">
    <p class="text-slate-800">
      {{ message }}
    </p>
  </div>
</template>
