<script setup lang="ts">
// * Data *

const message = "Hello, I'm a resource auto generated by Tricorder CLI!";

// * Methods *

function greeting() {
  alert(this.message);
}
</script>

<template>
  <div class="flex flex-col justify-start py-5 px-10">
    <header class="flex flex-row justify-between items-center content-center">
      <h2 class="text-slate-800 text-xl">ComponentName</h2>

      <button
        @click="greeting"
        class="text-white bg-sky-500 hover:bg-sky-700 py-1 px-2 rounded-lg"
      >
        Action
      </button>
    </header>

    <main class="flex justify-center items-center content-center">
      <p>{{ message }}</p>
    </main>
  </div>
</template>
