<script>
export default {
  name: 'ResourceName',
  components: {},
  filters: {},
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Clingon CLI!"
    }
  },
  props: {},
  methods: {}
}
</script>

<template>
  <div class="component">
    <p class="message">
      {{ message }}
    </p>
  </div>
</template>

<style scoped>
.component {
  display: flex;
  justify-content: center;
  align-items: center;
}

.message {
  color: #333;
}
</style>
