<script>
export default {
  name: 'ResourceName',
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Clingon CLI!"
    }
  }
}
</script>

<template>
  <div>
    <p>
      {{ message }}
    </p>
  </div>
</template>
