<script>
export default {
  name: 'ResourceName',
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Clingon CLI!"
    }
  }
}
</script>

<template>
  <div class="flex justify-center items-center">
    <p class="text-slate-800">
      {{ message }}
    </p>
  </div>
</template>
