import { render, screen } from "@testing-library/react";
import { describe, it, expect } from "vitest";

import { ResourceName } from "componentPath";

describe("ResourceName", () => {
  it("renders welcome message", () => {
    render(<ResourceName />);

    expect(
      screen.getByText(
        "Hello, I'm a component, auto generated by Tricorder CLI!"
      )
    ).toBeInTheDocument();
  });
});
