- identifier: component
  folderWrapper: true
  case: 'PascalCase'
  resource:
    path: 'src/components'
    template: './ReactComponent/Component.tsx'
  test:
    path: 'src/components'
    template: './ReactComponent/Component.test.tsx'
  story:
    path: 'src/components'
    template: './ReactComponent/Component.stories.tsx'

- identifier: async-function
  case: 'kebab-case'
  resource:
    path: src/utils
    template: './functions/AsyncFunction.ts'
  test:
    path: src/utils
    template: './functions/AsyncFunction.spec.ts'

- identifier: markdown
  case: 'UPPERCASE'
  resource:
    path: src/docs
    template: './docs/ReactHookDoc.md'

- identifier: nvmrc
  resource:
    path: .
    template: './Core/.nvmrc'
