<template>
  <div class="component">
    <div class="message">
      {{ message }}
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'ResourceName',
  methods: {},
  computed: {},
  watch: {},
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Clingon CLI!"
    }
  },
  beforeMounted() {},
  mounted() {},
  beforeCreated() {},
  created() {},
  beforeUpdated() {},
  updated() {}
})
</script>

<style scoped>
.component {
  display: flex;
  justify-content: center;
  align-items: center;
}

.message {
  color: #333;
}
</style>
