<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'ResourceName',
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Clingon CLI!"
    }
  }
})
</script>

<template>
  <div>
    <p>
      {{ message }}
    </p>
  </div>
</template>
