<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'ResourceName',
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Clingon CLI!"
    }
  }
})
</script>

<template>
  <div class="component">
    <p class="message">
      {{ message }}
    </p>
  </div>
</template>

<style scoped>
.component {
  display: flex;
  justify-content: center;
  align-items: center;
}

.message {
  color: #333;
}
</style>
