<script>
export default {
  name: "ComponentName",
  props: {},
  components: {},
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Tricorder CLI!",
    };
  },
  methods: {},
  computeds: {},
  watch: {},
  beforeMounted() {},
  mounted() {},
  beforeCreated() {},
  created() {},
  beforeUpdated() {},
  updated() {},
};
</script>

<template>
  <div class="component">
    <p class="paragraph">
      {{ message }}
    </p>
  </div>
</template>

<style scoped lang="scss">
.component {
  display: flex;
  justify-content: center;
  align-items: center;

  .paragraph {
    color: #333;
  }
}
</style>
