<script setup lang="ts">
const message = "Hello, I'm a resource auto generated by Tricorder CLI!";
</script>

<template>
  <div class="testpage">
    <p class="paragraph">
      {{ message }}
    </p>
  </div>
</template>

<style scoped>
.testpage {
  display: flex;
  justify-content: center;
  align-items: center;
}

.paragraph {
  color: #333;
}
</style>
