<template>
  <div class="testv2optts">
    <div class="paragraph">
      {{ message }}
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "ComponentName",
  testv2opttss: {},
  filters: {},
  props: {},
  methods: {},
  computeds: {},
  watch: {},
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Tricorder CLI!",
    };
  },
  beforeMounted() {},
  mounted() {},
  beforeCreated() {},
  created() {},
  beforeUpdated() {},
  updated() {},
});
</script>

<style>
.testv2optts {
  display: flex;
  justify-content: center;
  align-items: center;
}

.paragraph {
  color: #333;
}
</style>
