<script setup>
// * Data *

const message = "Hello, I'm a resource auto generated by Clingon CLI!"

// * Methods *

function greeting() {
  alert(this.message)
}
</script>

<template>
  <div class="page">
    <header class="header">
      <h2 class="title">ResourceName</h2>

      <button @click="greeting" class="action">Action</button>
    </header>

    <main class="content">
      <p>{{ message }}</p>
    </main>
  </div>
</template>

<style scoped lang="scss">
.page,
.header,
.content {
  display: flex;
}

.header,
.content {
  align-items: center;
  align-content: center;
}

.page {
  flex-direction: column;
  justify-content: flex-start;
  padding: 20px 40px;

  .header {
    flex-direction: row;
    justify-content: space-between;

    .title {
      color: #333;
      font-size: x-large;
    }

    .action {
      color: #fff;
      background-color: #1c77f7;

      padding: 4px 8px;
      border-radius: 8px;

      &:hover {
        background-color: #0758c9;
      }
    }
  }

  .content {
    justify-content: center;
  }
}
</style>
