import { render, screen } from '@testing-library/vue'

import ResourceName from 'resourcePath'

describe('ResourceName', () => {
  const componentData = {
    props: {},
    slots: {}
  }

  it('renders the correct message', () => {
    render(ResourceName, componentData)

    expect(
      screen.getByText("Hello, I'm a resource auto generated by Tricorder CLI!")
    ).toBeInTheDocument()
  })
})
