import { shallowMount } from '@vue/test-utils'

import ResourceName from 'resourcePath'

describe('ResourceName', () => {
  const wrapper = shallowMount(ResourceName)

  it('renders the correct message', () => {
    expect(wrapper.text()).toBe("Hello, I'm a resource auto generated by Clingon CLI!")
  })
})
