import { render, screen } from "@testing-library/react";

import { ResourceName } from "componentPath";

type RenderComponent = {
  props: InstanceType<typeof ResourceName>["$props"];
  slots: InstanceType<typeof ResourceName>["$slots"];
};

describe("ResourceName", () => {
  const componentData: RenderComponent = {
    props: {},
    slots: {},
  };

  it("renders the correct message", () => {
    render(ResourceName, componentData);

    expect(
      screen.getByText("Hello, I'm a resource auto generated by Tricorder CLI!")
    ).toBeInTheDocument();
  });
});
