import { render, screen } from "@testing-library/react";

import { describe, it, expect } from "vitest";

import { ComponentName } from "componentPath";

type RenderComponent = {
  props: InstanceType<typeof ComponentName>["$props"];
  slots: InstanceType<typeof ComponentName>["$slots"];
};

describe("ComponentName", () => {
  const componentData: RenderComponent = {
    props: {},
    slots: {},
  };

  it("renders the correct message", () => {
    render(ComponentName, componentData);

    expect(
      screen.getByText("Hello, I'm a resource auto generated by Tricorder CLI!")
    ).toBeInTheDocument();
  });
});
