import { shallowMount } from "@vue/test-utils";

import { describe, it, expect } from "vitest";

import { ResourceName } from "componentPath";

describe("ResourceName", () => {
  const wrapper = shallowMount(ResourceName);

  it("renders the correct message", () => {
    expect(wrapper.text()).toBe(
      "Hello, I'm a resource auto generated by Tricorder CLI!"
    );
  });
});
