import { render, screen } from "@testing-library/react";

import { ComponentName } from "componentPath";

describe("ComponentName", () => {
  const componentData = {
    props: {},
    slots: {},
  };

  it("renders the correct message", () => {
    render(ComponentName, componentData);

    expect(
      screen.getByText("Hello, I'm a resource auto generated by Tricorder CLI!")
    ).toBeInTheDocument();
  });
});
