import "./ResourceName.css";

export function ResourceName() {
  return (
    <div className="component">
      <p className="message">
        Hello, I'm a component, auto generated by Tricorder CLI!
      </p>
    </div>
  );
}
