import "./ComponentName.css";

export function ComponentName() {
  return (
    <div className="component">
      <p className="paragraph">
        Hello, I'm a component, auto generated by Tricorder CLI!
      </p>
    </div>
  );
}
