export type ResourceNameProps = {
  id: string
}

export function ResourceName({ id }: Props) {
  return (
    <div id={id} className="flex flex-row justify-center items-center content-center">
      <p className="text-slate-900 text-lg">
        Hello, I'm a component, auto generated by Clingon CLI!
      </p>
    </div>
  )
}
