export function ResourceName() {
  return (
    <div className="flex flex-row justify-center items-center content-center">
      <p className="text-slate-900 text-lg">
        Hello, I'm a component, auto generated by Tricorder CLI!
      </p>
    </div>
  )
}
