<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "ResourceName",
  components: {},
  filters: {},
  data() {
    return {
      message: "Hello, I'm a resource auto generated by Tricorder CLI!",
    };
  },
  props: {},
  methods: {
    greeting() {
      alert(this.message);
    },
  },
  computed: {},
  watch: {},
  beforeMounted() {},
  mounted() {},
  beforeCreated() {},
  created() {},
  beforeUpdated() {},
  updated() {},
});
</script>

<template>
  <div class="page">
    <header class="header">
      <h2 class="title">ResourceName</h2>

      <button @click="greeting" class="action">Action</button>
    </header>

    <main class="content">
      <p>{{ message }}</p>
    </main>
  </div>
</template>

<style scoped>
.page,
.header,
.content {
  display: flex;
}

.header,
.content {
  align-items: center;
  align-content: center;
}

.page {
  flex-direction: column;
  justify-content: flex-start;
  padding: 20px 40px;
}

.header {
  flex-direction: row;
  justify-content: space-between;
}

.content {
  justify-content: center;
}

.title {
  color: #333;
  font-size: x-large;
}

.action {
  color: #fff;
  background-color: #1c77f7;

  padding: 4px 8px;
  border-radius: 8px;
}

.action:hover {
  background-color: #0758c9;
}
</style>
