<script setup lang="ts">
// * Data *

const message = "Hello, I'm a resource auto generated by Clingon CLI!"

// * Methods *

function greeting(): void {
  alert(this.message)
}
</script>

<template>
  <div>
    <header>
      <h2>ResourceName</h2>

      <button @click="greeting">Action</button>
    </header>

    <main>
      <p>{{ message }}</p>
    </main>
  </div>
</template>
