<script setup lang="ts">
// * Data *

const message = "Hello, I'm a resource auto generated by Tricorder CLI!";

// * Methods *

function greeting() {
  alert(this.message);
}
</script>

<template>
  <div class="page">
    <header class="header">
      <h2 class="title">ResourceName</h2>

      <button @click="greeting" class="action">Action</button>
    </header>

    <main class="content">
      <p>{{ message }}</p>
    </main>
  </div>
</template>

<style scoped>
.page {
  @apply flex flex-col justify-start;
  @apply py-5 px-10;
}

.header {
  @apply flex flex-row justify-between items-center content-center;
}

.title {
  @apply text-slate-800 text-xl;
}

.content {
  @apply flex justify-center items-center content-center;
}

.action {
  @apply text-white bg-sky-500;
  @apply hover:bg-sky-700;
  @apply py-1 px-2;
  @apply rounded-lg;
}
</style>
