import styles from './ResourceName.css'

export function ResourceName({ id }) {
  return (
    <div id={id} className={styles.component}>
      <p className={styles.message}>Hello, I'm a component, auto generated by Clingon CLI!</p>
    </div>
  )
}
