import styles from "./ResourceName.css";

export function ResourceName() {
  return (
    <div className={styles.component}>
      <p className={styles.message}>
        Hello, I'm a component, auto generated by Tricorder CLI!
      </p>
    </div>
  );
}
