import './ResourceName.css'

export function ResourceName({ id }) {
  return (
    <div id={id} className="component">
      <p className="message">Hello, I'm a component, auto generated by Clingon CLI!</p>
    </div>
  )
}
